=== projectAccounth/better_clouds/common/src/main/resources/assets/cloud_tweaks/api/type_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "TypeDefinition",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "generator": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "native",
                        "custom"
                    ]
                },
                "base": {
                    "type": "string"
                },
                "outline": {
                    "type": "string"
                }
            },
            "if": {
                "properties": {
                    "type": {
                        "const": "custom"
                    }
                },
                "required": [
                    "type"
                ]
            },
            "then": {
                "required": [
                    "base"
                ]
            },
            "else": {
                "not": {
                    "required": [
                        "base"
                    ]
                }
            }
        },
        "render": {
            "type": "object",
            "properties": {
                "depth": {
                    "type": "boolean"
                },
                "outline_available": {
                    "type": "boolean"
                }
            }
        },
        "config": {
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "string",
                                "number",
                                "integer",
                                "boolean",
                                "object",
                                "array"
                            ]
                        },
                        "description": {
                            "type": "string"
                        },
                        "const": {
                            "type": [
                                "string",
                                "number",
                                "boolean",
                                "array",
                                "object",
                                "null"
                            ]
                        },
                        "enum": {
                            "type": "array",
                            "items": {
                                "type": [
                                    "string"
                                ]
                            }
                        },
                        "minimum": {
                            "type": "number"
                        },
                        "maximum": {
                            "type": "number"
                        },
                        "default": {
                            "type": [
                                "string",
                                "number",
                                "boolean",
                                "array",
                                "object",
                                "null"
                            ]
                        }
                    },
                    "required": [
                        "type"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "required": [
        "name",
        "generator",
        "render",
        "config"
    ]
}

=== projectAccounth/better_clouds/common/src/main/resources/assets/cloud_tweaks/api/types/beveled.json
{
    "name": "BEVELED",
    "generator": {
        "type": "native"
    },
    "render": {
        "outline_available": false,
        "depth": true
    },
    "config": {
        "BEVEL_SIZE": {
            "type": "number",
            "default": 1.5,
            "minimum": 0.1,
            "maximum": 8.0
        },
        "BEVEL_CORNER_SEGMENTS": {
            "type": "integer",
            "default": 8,
            "minimum": 1,
            "maximum": 32
        },
        "BEVEL_EDGE_SEGMENTS": {
            "type": "integer",
            "default": 8,
            "minimum": 1,
            "maximum": 32
        }
    }
}

=== projectAccounth/better_clouds/common/src/main/resources/assets/cloud_tweaks/api/types/example.json
{
    "name": "EXAMPLE",
    "generator": {
        "type": "custom",
        "base": "example"
    },
    "render": {
        "outline_available": false,
        "depth": true
    },
    "config": {
        "TEST_BOOL": {
            "type": "boolean",
            "default": false
        }
    }
}
